### ISSUE TITLE
display port or hdmi 2.0

### ISSUE THREAD

**Issue by kolanski** [yusufklncc/Huawei-Matebook-13-Hackintosh#1]
Hi, do you tested hdmi or dp with 4k display? Is it works?

**Comment by atmqca** [comment]
Hi, we tested it on 4k TV and it works.

**Comment by yusufklncc** [comment]
No 4K HDMI doesn't works. Maximum 1080p native. Advanced resolutions with HIDPI

**Comment by espitgn** [comment]
Hi! If you want to have 4K, you must hack BIOS. Look at [https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh/blob/master/readme-en.md] ,in "change dvmt to 64 mb" section. It runs. 

It's a good idea to improve power management disabling CFG Lock, too. Lock at the same link or in this repo.

Cheers!
