### ISSUE TITLE
AirportItlwm.kext can not running on MacOS Ventura.

### ISSUE THREAD

**Issue by yaleax** [yusufklncc/Huawei-Matebook-13-Hackintosh#2]
AirportItlwm.kext can not running on MacOS Ventura.

When I try Itlwm.kext and HeliPort, it is worked.

My computer is Matebook 13 2020.

Left type-c Only the charge works.

**Comment by yusufklncc** [comment]
![image](https://user-images.githubusercontent.com/78423442/204766431-87e67385-8e90-4709-ae21-d4b6868ed733.png)
my efi is for Monterey. If you are using ventura you have to change kext and set kext's maxkernel value to 22.9.9

**Comment by yaleax** [comment]
> ![image](https://user-images.githubusercontent.com/78423442/204766431-87e67385-8e90-4709-ae21-d4b6868ed733.png) my efi is for Monterey. If you are using ventura you have to change kext and set kext's maxkernel value to 22.9.9
worked. Thanks

**Comment by yaleax** [comment]
worked,Thanks
